/*
 * PCMD3180 Arduino Library
 *
 * The PCMD3180 is a multi-channel PDM-to-PCM converter with I2C control
 */

#ifndef PCMD3180_H
#define PCMD3180_H

#include <Arduino.h>
#include <Wire.h>

// Default I2C address (set by the ADDR pins; see datasheet 6.5.1.1)
#define PCMD3180_I2C_ADDR_DEFAULT 0x4C

// Default SHDNZ pin is no pin, assumed to be set by an external source
#define PCMD3180_SHDNZ_PIN_DEFAULT 0xFF

// ASI_CFG0 (0x07) ASI_FORMAT, bits [7:6]
enum AudioFormat {
  FORMAT_TDM,             // 0x00  TDM
  FORMAT_I2S,             // 0x40  I2S
  FORMAT_LEFT_JUSTIFIED,  // 0x80  Left-justified (LJ)
};

// ASI_CFG0 (0x07) ASI_WLEN, bits [5:4]
enum WordLength {
  WORD_16_BIT,  // 0x00
  WORD_20_BIT,  // 0x10
  WORD_24_BIT,  // 0x20
  WORD_32_BIT   // 0x30  (reset default)
};

// ASI_CFG0 (0x07) TX_EDGE, bit [1]
enum ASITXEdge {
  ASI_TX_EDGE_DEFAULT,   // 0x00  Default edge as per the protocol and BCLK_POL setting (reset default)
  ASI_TX_EDGE_INVERTED   // 0x02  Inverted following edge (half cycle delay) with respect to the default edge
};

// ASI_CFG0 (0x07) TX_FILL, bit [0]
// Data output (primary and secondary pin) during unused cycles
enum ASITXFill {
  ASI_TX_FILL_ZERO,  // 0x00  Always transmit 0 for unused cycles (reset default)
  ASI_TX_FILL_HI_Z   // 0x01  Always use Hi-Z for unused cycles
};

// ASI_CFG1 (0x08) TX_LSB, bit [7]
// Data output (primary and secondary pin) for LSB transmissions
enum ASITXLSB {
  ASI_TX_LSB_FULL_CYCLE,  // 0x00  Transmit the LSB for a full cycle (reset default)
  ASI_TX_LSB_HALF_CYCLE   // 0x80  Transmit the LSB for the first half cycle and Hi-Z for the second half
};

// ASI_CFG1 (0x08) TX_KEEPER, bits [6:5]
// Bus keeper on the data output (primary and secondary pin)
enum ASIBusKeeper {
  ASI_BUS_KEEPER_DISABLED,            // 0x00  Always disabled (reset default)
  ASI_BUS_KEEPER_ALWAYS,              // 0x20  Always enabled
  ASI_BUS_KEEPER_LSB_ONE_CYCLE,       // 0x40  Enabled during LSB transmissions only, for one cycle
  ASI_BUS_KEEPER_LSB_ONE_HALF_CYCLES  // 0x60  Enabled during LSB transmissions only, for one and a half cycles
};

// ASI_CFG0 (0x07) FSYNC_POL bit [3] or BCLK_POL bit [2], depending on which argument is being set
enum ASIPolarity {
  ASI_POLARITY_STANDARD,  // bit clear  Default polarity as per standard protocol
  ASI_POLARITY_INVERTED   // bit set    Inverted polarity with respect to standard protocol
};

// PDMCLK_CFG (0x1F) PDMCLK_DIV, bits [1:0]
// The datasheet gives two frequencies per setting, e.g. "2.8224MHz or 3.072MHz".
// setPDMClock() writes 0x40 to the reserved bits [7:2], which is their reset value.
enum PDMClock {
  PDMCLK_2822_KHZ,  // 0x00  2.8224 MHz or 3.072 MHz
  PDMCLK_1411_KHZ,  // 0x01  1.4112 MHz or 1.536 MHz
  PDMCLK_705_KHZ,   // 0x02  705.6 kHz or 768 kHz
  PDMCLK_5644_KHZ   // 0x03  5.6448 MHz or 6.144 MHz
};

// MST_CFG1 (0x14) FS_RATE, bits [7:4]
// Each value covers a 44.1 kHz-family and a 48 kHz-family rate; MST_CFG0 FS_MODE selects which.
// Not used when the device is in slave mode with auto clock configuration.
// ASI_STS (0x15) FS_RATE_STS bits [7:4] uses the same encoding (see getAutodetectedClocks()).
enum FSRate {
  FSRATE_8,    // 0x00  7.35 kHz or 8 kHz
  FSRATE_16,   // 0x10  14.7 kHz or 16 kHz
  FSRATE_24,   // 0x20  22.05 kHz or 24 kHz
  FSRATE_32,   // 0x30  29.4 kHz or 32 kHz
  FSRATE_48,   // 0x40  44.1 kHz or 48 kHz  (reset default)
  FSRATE_96,   // 0x50  88.2 kHz or 96 kHz
  FSRATE_192,  // 0x60  176.4 kHz or 192 kHz
  FSRATE_384,  // 0x70  352.8 kHz or 384 kHz
  FSRATE_768   // 0x80  705.6 kHz or 768 kHz
};

// MST_CFG1 (0x14) FS_BCLK_RATIO, bits [3:0]
// Not used when the device is in slave mode with auto clock configuration.
// Note: BCLK cycles per frame must be >= active output channels * word length (datasheet 6.3.1.2)
enum BCLKRatio {
  BCLKRATIO_16,    // 0x00
  BCLKRATIO_24,    // 0x01
  BCLKRATIO_32,    // 0x02
  BCLKRATIO_48,    // 0x03
  BCLKRATIO_64,    // 0x04
  BCLKRATIO_96,    // 0x05
  BCLKRATIO_128,   // 0x06
  BCLKRATIO_192,   // 0x07
  BCLKRATIO_256,   // 0x08  (reset default)
  BCLKRATIO_384,   // 0x09
  BCLKRATIO_512,   // 0x0A
  BCLKRATIO_1024,  // 0x0B
  BCLKRATIO_2048,  // 0x0C
};

// CLK_SRC (0x16) DIS_PLL_SLV_CLK_SRC, bit [7]
// Audio root clock source in slave mode when the auto-mode PLL is disabled
enum PLLSlaveClockSource {
  PLLSLAVECLKSRC_BCLK,  // 0x00  BCLK
  PLLSLAVECLKSRC_MCLK   // 0x80  MCLK (GPIO1 or GPIx)
};

// MST_CFG0 (0x13) MST_SLV_CFG, bit [7]
enum MasterMode {
  MODE_SLAVE,   // 0x00  BCLK and FSYNC are inputs to the device
  MODE_MASTER   // 0x80  BCLK and FSYNC are generated by the device
};

// MST_CFG0 (0x13) FS_MODE, bit [3]  (valid in master mode)
enum FSMode {
  FSYNC_MODE_48000,  // 0x00  fS is a multiple (or submultiple) of 48 kHz
  FSYNC_MODE_44100   // 0x08  fS is a multiple (or submultiple) of 44.1 kHz
};

// MST_CFG0 (0x13) MCLK_FREQ_SEL, bits [2:0]
// MCLK (GPIO1 or GPIx) frequency for the PLL in master mode, used when CLK_SRC MCLK_FREQ_SEL_MODE = 0
enum MCLKFrequency {
  MCLK_FREQ_12000_KHZ,  // 0x00  12 MHz
  MCLK_FREQ_12288_KHZ,  // 0x01  12.288 MHz
  MCLK_FREQ_13000_KHZ,  // 0x02  13 MHz  (reset default)
  MCLK_FREQ_16000_KHZ,  // 0x03  16 MHz
  MCLK_FREQ_19200_KHZ,  // 0x04  19.2 MHz
  MCLK_FREQ_19680_KHZ,  // 0x05  19.68 MHz
  MCLK_FREQ_24000_KHZ,  // 0x06  24 MHz
  MCLK_FREQ_24576_KHZ   // 0x07  24.576 MHz
};

// CLK_SRC (0x16) MCLK_RATIO_SEL, bits [5:3]
// MCLK (GPIO1 or GPIx) to FSYNC ratio, for master mode or when MCLK is the audio root clock in slave mode
enum MCLKRatio {
  MCLKRATIO_64,    // 0x00
  MCLKRATIO_256,   // 0x08
  MCLKRATIO_384,   // 0x10  (reset default)
  MCLKRATIO_512,   // 0x18
  MCLKRATIO_768,   // 0x20
  MCLKRATIO_1024,  // 0x28
  MCLKRATIO_1536,  // 0x30
  MCLKRATIO_2304   // 0x38
};

// GPIO_CFG0 (0x21) GPIO1_CFG, bits [7:4]
enum GPIOMode {
  GPIO_MODE_DISABLED,   // 0x00
  GPIO_MODE_GPO,        // 0x10  General-purpose output
  GPIO_MODE_IRQ,        // 0x20  Interrupt output (reset default)
  GPIO_MODE_SDOUT2,     // 0x30  Secondary ASI output
  GPIO_MODE_PDMCLK,     // 0x40  PDM clock output
  GPIO_MODE_MICBIAS_EN, // 0x80  Input that controls when MICBIAS turns on or off
  GPIO_MODE_GPI,        // 0x90  General-purpose input
  GPIO_MODE_MCLK,       // 0xA0  Master clock input
  GPIO_MODE_SDIN,       // 0xB0  ASI input for daisy-chain
  GPIO_MODE_PDMDIN1,    // 0xC0  PDM data input for channels 1 and 2
  GPIO_MODE_PDMDIN2,    // 0xD0  PDM data input for channels 3 and 4
  GPIO_MODE_PDMDIN3,    // 0xE0  PDM data input for channels 5 and 6
  GPIO_MODE_PDMDIN4     // 0xF0  PDM data input for channels 7 and 8
};

// GPIO_CFG0 (0x21) GPIO1_DRV bits [2:0] / GPO_CFG0..3 (0x22-0x25) GPOx_DRV bit [0]
// Note: GPO ports only support DRIVE_MODE_HI_Z and DRIVE_MODE_ACTIVE_LOW_ACTIVE_HIGH
enum DriveMode {
  DRIVE_MODE_HI_Z,                    // 0x00  Hi-Z output
  DRIVE_MODE_ACTIVE_LOW_ACTIVE_HIGH,  // 0x01  Drive active low and active high
  DRIVE_MODE_ACTIVE_LOW_WEAK_HIGH,    // 0x02  Drive active low and weak high (GPIO only, GPIO reset default)
  DRIVE_MODE_ACTIVE_LOW_HI_Z,         // 0x03  Drive active low and Hi-Z (GPIO only)
  DRIVE_MODE_WEAK_LOW_ACTIVE_HIGH,    // 0x04  Drive weak low and active high (GPIO only)
  DRIVE_MODE_HI_Z_ACTIVE_HIGH         // 0x05  Drive Hi-Z and active high (GPIO only)
};

// GPO_CFG0..3 (0x22-0x25) GPOx_CFG, bits [7:4]  (one register per port)
enum GPOMode {
  GPO_MODE_DISABLED,  // 0x00  (reset default)
  GPO_MODE_GPO,       // 0x10  General-purpose output
  GPO_MODE_IRQ,       // 0x20  Interrupt output
  GPO_MODE_ASI,       // 0x30  Secondary ASI output (SDOUT2)
  GPO_MODE_PDM        // 0x40  PDM clock output (PDMCLK)
};

// GPI_CFG0 (0x2B, ports 1-2) and GPI_CFG1 (0x2C, ports 3-4); odd ports bits [6:4], even ports bits [2:0]
enum GPIMode {
  GPI_MODE_DISABLED,  // 0x00  (reset default)
  GPI_MODE_GPI,       // 0x01  General-purpose input
  GPI_MODE_MCLK,      // 0x02  Master clock input
  GPI_MODE_ASI,       // 0x03  ASI input for daisy-chain (SDIN)
  GPI_MODE_PDMDIN1,   // 0x04  PDM data input for channels 1 and 2
  GPI_MODE_PDMDIN2,   // 0x05  PDM data input for channels 3 and 4
  GPI_MODE_PDMDIN3,   // 0x06  PDM data input for channels 5 and 6
  GPI_MODE_PDMDIN4    // 0x07  PDM data input for channels 7 and 8
};

// BIAS_CFG (0x3B) MBIAS_VAL, bits [6:4]
enum MICBIASMode {
  MICBIAS_MODE_VREF,  // 0x00  Microphone bias is set to VREF (reset default)
  MICBIAS_MODE_AVDD   // 0x60  Microphone bias is set to AVDD
};

// Not written to a register directly; selects whether wakeUp() changes the VREF setting
enum AVDDInputVoltage {
  AVDD_INPUT_18V,  // wakeUp() sets VREF to 1.375 V (BIAS_CFG bits [1:0] = 0x02)
  AVDD_INPUT_33V   // wakeUp() leaves VREF unchanged (reset default 2.75 V)
};

// BIAS_CFG (0x3B) VREF_SEL, bits [1:0]
// Note: configure based on the minimum AVDD supply voltage; VREF_MODE_1375V must be used for 1.8 V AVDD
enum VREFMode {
  VREF_MODE_275V,   // 0x00  2.75 V  (reset default)
  VREF_MODE_25V,    // 0x01  2.5 V
  VREF_MODE_1375V   // 0x02  1.375 V
};

// ASI_CH1..8 (0x0B-0x12) CHx_OUTPUT, bit [6]
// Note: the secondary output is GPIO1 or a GPOx pin; configure it as GPIO_MODE_SDOUT2 or GPO_MODE_ASI
enum ASIPin {
  ASIPIN_PRIMARY,    // 0x00  Primary output pin (SDOUT)
  ASIPIN_SECONDARY   // 0x40  Secondary output pin (GPIO1 or GPOx)
};

// INT_CFG (0x32) INT_EVENT, bits [6:5]
enum INTMode {
  INT_MODE_ASSERT_CONSTANT,    // 0x00  Asserts on any unmasked latched interrupt event
  INT_MODE_ASSERT_2MS_PULSED,  // 0x40  Asserts for 2 ms in every 4 ms on any unmasked latched interrupt event
  INT_MODE_ASSERT_2MS_ONCE     // 0x60  Asserts for 2 ms once on each pulse for any unmasked interrupt event
};

// INT_CFG (0x32) LTCH_READ_CFG, bit [2]
enum INTLatchReadMode {
  INT_LATCH_MODE_READ_ALL,            // 0x00  All interrupts can be read through INT_LTCH0
  INT_LATCH_MODE_READ_ONLY_UNMASKED   // 0x04  Only unmasked interrupts can be read through INT_LTCH0
};

// INT_CFG (0x32) INT_POL, bit [7]
enum INTPolarity {
  INT_POLARITY_ACTIVE_LOW,   // 0x00  (reset default)
  INT_POLARITY_ACTIVE_HIGH   // 0x80
};

// DSP_CFG0 (0x6B) DECI_FILT, bits [5:4]  (filter responses: datasheet 6.3.6.7)
enum FilterMode {
  FILTER_MODE_LINEAR,             // 0x00  Linear phase (reset default)
  FILTER_MODE_LOW_LATENCY,        // 0x10  Low latency
  FILTER_MODE_ULTRA_LOW_LATENCY   // 0x20  Ultra-low latency
};

// DSP_CFG0 (0x6B) CH_SUM, bits [3:2]
enum SummationMode {
  SUMMATION_MODE_DISABLED,  // 0x00  (reset default)
  SUMMATION_MODE_2CHAN,     // 0x04  Outputs (CH1 + CH2) / 2 and (CH3 + CH4) / 2
  SUMMATION_MODE_4CHAN      // 0x08  Outputs (CH1 + CH2 + CH3 + CH4) / 4
};

// DSP_CFG0 (0x6B) HPF_SEL, bits [1:0]
enum HPFilterMode {
  HP_FILTER_MODE_CUSTOM,  // 0x00  Programmable first-order IIR (coefficients P4_R72 to P4_R83, default all-pass)
  HP_FILTER_MODE_12HZ,    // 0x01  Cutoff 0.00025 x fS (12 Hz at 48 kHz, reset default)
  HP_FILTER_MODE_96HZ,    // 0x02  Cutoff 0.002 x fS (96 Hz at 48 kHz)
  HP_FILTER_MODE_384HZ    // 0x03  Cutoff 0.008 x fS (384 Hz at 48 kHz)
};

// PDMIN_CFG (0x20) PDMDINx_EDGE: one bit per port (bit 7 = port 1, bit 6 = port 2, ...)
// Each PDM port carries two channels on one data line; the odd channel is latched on one edge, the even on the other
enum EdgeLatchMode {
  EDGE_MODE_EVEN_POSITIVE,  // 0  Even-numbered channel latched on the rising edge (reset default)
  EDGE_MODE_EVEN_NEGATIVE   // 1  Even-numbered channel latched on the falling edge
};

// SLEEP_CFG (0x02) VREF_QCHG, bits [4:3]
// Duration of the quick-charge of the external VREF capacitor
enum VREFChargeDuration {
  VREF_CHARGE_DURATION_35,   // 0x00  3.5 ms (reset default)
  VREF_CHARGE_DURATION_10,   // 0x08  10 ms
  VREF_CHARGE_DURATION_50,   // 0x10  50 ms
  VREF_CHARGE_DURATION_100,  // 0x18  100 ms
};

// SHDN_CFG (0x05) SHDNZ_CFG, bits [3:2]
// Behaviour of DREG after the SHDNZ pin is asserted
enum ShutdownMode {
  SHUTDOWN_DREG_IMMEDIATELY,            // 0x00  DREG is powered down immediately
  SHUTDOWN_DREG_ACTIVE_UNTIL_TIMEOUT,   // 0x04  DREG stays active until the DREG_KA_TIME timeout, then is forced off (reset default)
  SHUTDOWN_DREG_ACTIVE_UNTIL_SHUTDOWN   // 0x08  DREG stays active until the device cleanly shuts down
};

// SHDN_CFG (0x05) DREG_KA_TIME, bits [1:0]
// Note: register encoding is inverted (5 ms = 0x03, 30 ms = 0x00)
enum DREGActiveTime {
  DREG_ACTIVE_TIME_5,   // 0x03   5 ms
  DREG_ACTIVE_TIME_10,  // 0x02  10 ms
  DREG_ACTIVE_TIME_25,  // 0x01  25 ms (reset default)
  DREG_ACTIVE_TIME_30   // 0x00  30 ms
};

// PWR_CFG (0x75) DYN_MAXCH_SEL, bits [3:2]
enum DynamicPowerMode {
  DYNAMIC_POWER_ENABLE_CH1_TO_CH2,  // 0x00  (reset default)
  DYNAMIC_POWER_ENABLE_CH1_TO_CH4,  // 0x04
  DYNAMIC_POWER_ENABLE_CH1_TO_CH6,  // 0x08
  DYNAMIC_POWER_ENABLE_ALL_CH,      // 0x0C  Channels 1 to 8
};

class PCMD3180 {
public:
  /** Constructor for PCMD3180 device
   * @param shdnzPin GPIO pin for hardware shutdown control (0xFF if not used)
   * @param i2cAddr I2C address of the device (default 0x4C)
   * @param aregInternal True for the internally generated 1.8V AREG (use when
   *        AVDD is 3.3V), false for an external 1.8V AREG supply
   * @param avddInputVoltage Voltage being provided to the AVDD input pin.
   *        If AVDD_INPUT_18V, wakeUp() sets VREF to 1.375V
   * @note Only stores the parameters; the SHDNZ pin and the device are not
   *       touched until begin(). To hold the device in shutdown from power-on,
   *       pull SHDNZ low in hardware.
   */
  PCMD3180(uint8_t shdnzPin = PCMD3180_SHDNZ_PIN_DEFAULT,
           uint8_t i2cAddr = PCMD3180_I2C_ADDR_DEFAULT,
           bool aregInternal = false,
           AVDDInputVoltage avddInputVoltage = AVDD_INPUT_33V);

  /** Initialize the PCMD3180 device and perform basic setup
   * @param wire TwoWire interface to use (default Wire)
   * @return True if initialization successful, false otherwise
   * @note If a SHDNZ pin was given, sets it as an output and calls
   *       hardwarePowerDown() then hardwarePowerUp(). Then checks that the
   *       device acknowledges on I2C, then calls reset() and wakeUp(). See
   *       datasheet 6.4 "Device Functional Modes".
   */
  bool begin(TwoWire &wire = Wire);

  /** Perform software reset of the PCMD3180 device
   * @return True if reset successful, false otherwise
   * @note Writes 1 to SW_RESET (0x01) bit 0, which restores all registers to
   *       their defaults (datasheet 6.4.4), then waits 10ms.
   */
  bool reset();

  // -------------------------------------------------------------------------
  // Utility methods — use these for typical setups
  // -------------------------------------------------------------------------

  /** Configure the device as an I2S/TDM slave (host provides BCLK and FSYNC)
   * @param format Audio format (TDM, I2S, or Left Justified)
   * @param wordLen Word length (16, 20, 24, or 32 bits)
   * @param numChannels Number of channels to enable (1-8)
   * @return True if successful, false otherwise
   * @note Sets slave mode, enables auto clock configuration and the
   *       auto-mode PLL, sets the ASI format and calls enableAllChannels().
   *       Call configurePDMInput() and powerPDM() afterwards to complete setup.
   */
  bool configureAsSlave(AudioFormat format, WordLength wordLen, uint8_t numChannels);

  /** Configure the device as an I2S/TDM master (device drives BCLK and FSYNC)
   * @param format Audio format (TDM, I2S, or Left Justified)
   * @param wordLen Word length (16, 20, 24, or 32 bits)
   * @param fsyncRate FSYNC sample rate
   * @param bclkRatio BCLK-to-FSYNC ratio
   * @param numChannels Number of channels to enable (1-8)
   * @param mclkFreq Frequency of the MCLK supplied to the device
   * @return True if successful, false otherwise
   * @note Sets master mode, calls setMCLKFrequency(), setASIClock() and
   *       setASIFormat(), and calls enableAllChannels(). In master mode the
   *       PLL uses MCLK on GPIO1 or a GPIx pin as its reference (datasheet
   *       6.3.2); configure that pin with setGPIOConfig(GPIO_MODE_MCLK, ...)
   *       or setGPIMode(port, GPI_MODE_MCLK). The sample-rate family (48kHz
   *       or 44.1kHz) is set with setMasterConfig(). Call configurePDMInput()
   *       and powerPDM() afterwards to complete setup.
   */
  bool configureAsMaster(AudioFormat format, WordLength wordLen, FSRate fsyncRate, BCLKRatio bclkRatio, uint8_t numChannels, MCLKFrequency mclkFreq);

  /** Configure PDM clock and enable the required input ports and channels
   * @param clk PDM clock frequency
   * @param numChannels Number of channels to enable (1-8)
   * @return True if successful, false otherwise
   * @note Calls setPDMClock(). Then, for each port p = 1..(numChannels + 1) / 2,
   *       calls enablePort(p, true), sets GPOp to output PDMCLK (push-pull)
   *       and sets GPIp as PDMDINp. Then calls enableAllChannels(). This
   *       follows datasheet 8.2.1.2 and assumes each port's microphones are
   *       wired to PDMCLKp_GPOp and PDMDINp_GPIp. Does not power up the PDM
   *       block — call powerPDM(true) after this.
   */
  bool configurePDMInput(PDMClock clk, uint8_t numChannels);

  /** Enable a contiguous set of input and ASI output channels by count
   * @param numChannels Number of channels to enable, starting from channel 1
   * @return True if successful, false otherwise
   * @note Writes the same bitmask to IN_CH_EN (0x73) and ASI_OUT_CH_EN
   *       (0x74), with channel 1 as bit 7. Channels above numChannels are
   *       disabled.
   */
  bool enableAllChannels(uint8_t numChannels);

  /** Set the same digital volume on all eight channels
   * @param volume Volume value (0x00 = mute, 0xC9 = unity gain, 0xFF = +27dB)
   * @return True if successful, false otherwise
   * @note Calls setDigitalVolume() for each channel in sequence.  Stops and
   *       returns false immediately if any individual write fails.
   */
  bool setAllChannelVolumes(uint8_t volume);

  // -------------------------------------------------------------------------

  /** Enable or disable I2C broadcast mode for the device
   * @param enable True to enable broadcast, false to disable
   * @return True if successful, false otherwise
   * @note Sets SLEEP_CFG (0x02) I2C_BRDCAST_EN, bit 2. While enabled, the
   *       device responds at the fixed address 0x4C (1001 100) instead of the
   *       address set by the ADDR pins. See datasheet 6.3.1.3.
   */
  bool setI2CBroadcast(bool enable);

  /** Configure ASI audio format and word length
   * @param format Audio format (TDM, I2S, or Left Justified)
   * @param wordLen Word length (16, 20, 24, or 32 bits)
   * @return True if successful, false otherwise
   * @note Writes ASI_CFG0 (0x07) ASI_FORMAT bits 7:6 and ASI_WLEN bits 5:4.
   *       See datasheet 6.3.1.2.
   */
  bool setASIFormat(AudioFormat format, WordLength wordLen);

  /** Configure FSYNC and BCLK polarity for ASI interface
   * @param fsyncPolarity FSYNC polarity (standard or inverted)
   * @param bclkPolarity BCLK polarity (standard or inverted)
   * @return True if successful, false otherwise
   * @note Writes ASI_CFG0 (0x07) FSYNC_POL (bit 3) and BCLK_POL (bit 2).
   */
  bool setASIPolarities(ASIPolarity fsyncPolarity, ASIPolarity bclkPolarity);

  /** Set the BCLK edge on which ASI data is transmitted
   * @param edge Default edge, or inverted (half cycle delay)
   * @return True if successful, false otherwise
   * @note Writes ASI_CFG0 (0x07) TX_EDGE, bit 1.
   */
  bool setASITXEdge(ASITXEdge edge);

  /** Set what the ASI data output transmits during unused cycles
   * @param fill Transmit 0, or Hi-Z
   * @return True if successful, false otherwise
   * @note Writes ASI_CFG0 (0x07) TX_FILL, bit 0. Hi-Z lets other devices
   *       share the data line.
   */
  bool setASITXFill(ASITXFill fill);

  /** Set how long the LSB is driven on the ASI data output
   * @param lsb Full cycle, or half cycle followed by Hi-Z
   * @return True if successful, false otherwise
   * @note Writes ASI_CFG1 (0x08) TX_LSB, bit 7.
   */
  bool setASITXLSB(ASITXLSB lsb);

  /** Configure the bus keeper on the ASI data output
   * @param keeper Bus keeper mode
   * @return True if successful, false otherwise
   * @note Writes ASI_CFG1 (0x08) TX_KEEPER, bits 6:5.
   */
  bool setASIBusKeeper(ASIBusKeeper keeper);

  /** Offset the MSB of slot 0 from the standard protocol timing
   * @param offset Offset in BCLK cycles (0-31; reset default 0)
   * @return True if successful, false if offset is above 31
   * @note Writes ASI_CFG1 (0x08) TX_OFFSET, bits 4:0. In I2S/LJ mode the
   *       offset applies to both left and right slot 0. See datasheet
   *       6.3.1.2.
   */
  bool setASITXOffset(uint8_t offset);

  /** Configure ASI bus error detection and auto-resume
   * @param enableErrorDetection True to enable bus error detection
   * @param enableAutoResumeOnRecovery True to auto-resume after bus error
   *        recovery; false to stay powered down until the host reconfigures
   *        the device
   * @return True if successful, false otherwise
   * @note Writes ASI_CFG2 (0x09) ASI_ERR (bit 5) and ASI_ERR_RCOV (bit 4).
   *       Both are disable bits in the register (0 = enabled).
   */
  bool setASIErrorDetection(bool enableErrorDetection, bool enableAutoResumeOnRecovery);

  /** Enable or disable ASI daisy-chain mode
   * @param enableDaisyChain True if all devices are daisy-chained on the ASI
   *        bus, false if all devices share a common ASI bus
   * @return True if successful, false otherwise
   * @note Writes ASI_CFG2 (0x09) ASI_DAISY, bit 7. See datasheet 6.3.1.3.
   */
  bool setASIDaisyChained(bool enableDaisyChain);

  /** Set device to master or slave mode
   * @param masterMode MODE_SLAVE for slave mode, MODE_MASTER for master mode
   * @return True if successful, false otherwise
   * @note Writes MST_CFG0 (0x13) MST_SLV_CFG, bit 7. See datasheet 6.3.2.
   */
  bool setMasterMode(MasterMode masterMode);

  /** Configure master mode settings
   * @param enableGatedFsyncAndBclk True to force-gate BCLK and FSYNC when
   *        transmitted from the device in master mode
   * @param fsMode Sample-rate family (48kHz or 44.1kHz based)
   * @return True if successful, false otherwise
   * @note Writes MST_CFG0 (0x13) BCLK_FSYNC_GATE (bit 4) and FS_MODE (bit 3).
   *       Both are only valid in master mode.
   */
  bool setMasterConfig(bool enableGatedFsyncAndBclk, FSMode fsMode);

  /** Enable or disable automatic clock configuration
   * @param autoClockConfigEnabled True to enable auto clock config (reset default)
   * @return True if successful, false otherwise
   * @note Writes MST_CFG0 (0x13) AUTO_CLK_CFG, bit 6, which is a disable bit
   *       (0 = enabled). With it enabled, all internal clock dividers and PLL
   *       settings are derived automatically. See datasheet 6.3.2.
   */
  bool setAutoClockConfigEnabled(bool autoClockConfigEnabled);

  /** Enable or disable the PLL in auto clock configuration
   * @param pllEnabled True to enable the PLL (reset default), false to disable
   * @return True if successful, false otherwise
   * @note Writes MST_CFG0 (0x13) AUTO_MODE_PLL_DIS, bit 5, which is a disable
   *       bit (0 = enabled). See datasheet 6.3.2.
   */
  bool setAutoClockPLLEnabled(bool pllEnabled);

  /** Select the audio root clock source when the auto-mode PLL is disabled in slave mode
   * @param clkSource BCLK or MCLK as clock source
   * @return True if successful, false otherwise
   * @note Writes CLK_SRC (0x16) DIS_PLL_SLV_CLK_SRC, bit 7. Only applies when
   *       AUTO_MODE_PLL_DIS = 1 (see setAutoClockPLLEnabled()).
   */
  bool setDisabledPLLClockSource(PLLSlaveClockSource clkSource);

  /** Set the MCLK frequency used as the PLL reference in master mode
   * @param freq MCLK frequency (12MHz to 24.576MHz)
   * @return True if successful, false otherwise
   * @note Writes MST_CFG0 (0x13) MCLK_FREQ_SEL (bits 2:0) and clears CLK_SRC
   *       (0x16) MCLK_FREQ_SEL_MODE (bit 6), so the frequency is taken from
   *       MCLK_FREQ_SEL. Use setMCLKRatio() instead if MCLK is a multiple of
   *       FSYNC. See datasheet 6.3.2.
   */
  bool setMCLKFrequency(MCLKFrequency freq);

  /** Specify MCLK as a multiple of FSYNC
   * @param ratio MCLK to FSYNC ratio (64 to 2304)
   * @return True if successful, false otherwise
   * @note Writes CLK_SRC (0x16) MCLK_RATIO_SEL (bits 5:3) and sets
   *       MCLK_FREQ_SEL_MODE (bit 6), so in master mode the MCLK frequency is
   *       taken from the ratio instead of MCLK_FREQ_SEL. The ratio is also
   *       used in slave mode when MCLK is the audio root clock (see
   *       setDisabledPLLClockSource()). See datasheet 6.3.2.
   */
  bool setMCLKRatio(MCLKRatio ratio);

  /** Configure ASI bus clock in master mode
   * @param fsyncRate FSYNC sample rate (8kHz to 768kHz)
   * @param bclkRatio BCLK to FSYNC ratio (16 to 2048)
   * @return True if successful, false otherwise
   * @note Writes the whole MST_CFG1 (0x14) register: FS_RATE bits 7:4 and
   *       FS_BCLK_RATIO bits 3:0. Not used in slave mode with auto clock
   *       configuration. See datasheet 6.3.2.
   */
  bool setASIClock(FSRate fsyncRate, BCLKRatio bclkRatio);

  /** Configure PDM clock frequency
   * @param clk PDM clock frequency (see PDMClock)
   * @return True if successful, false otherwise
   * @note Writes PDMCLK_CFG (0x1F): PDMCLK_DIV bits 1:0, with the reserved
   *       bits set to their reset value. See datasheet 6.3.5.
   */
  bool setPDMClock(PDMClock clk);

  /** Configure GPIO1 pin function and drive mode
   * @param mode GPIO function mode (GPO, IRQ, PDMCLK, etc.)
   * @param driveMode Output drive configuration (not used in SDOUT2 mode)
   * @return True if successful, false otherwise
   * @note Writes the whole GPIO_CFG0 (0x21) register: GPIO1_CFG bits 7:4 and
   *       GPIO1_DRV bits 2:0. See datasheet 6.3.7.
   */
  bool setGPIOConfig(GPIOMode mode, DriveMode driveMode);

  /** Set GPIO1 output value (when configured as GPO)
   * @param driveHigh True to drive high, false to drive low
   * @return True if successful, false otherwise
   * @note Writes GPO_VAL (0x29) GPIO1_VAL, bit 7.
   */
  bool setGPIOVal(bool driveHigh);

  /** Set GPO port output value (when configured as GPO)
   * @param port GPO port number (1-4)
   * @param driveHigh True to drive high, false to drive low
   * @return True if successful, false otherwise
   * @note Writes GPO_VAL (0x29) GPOx_VAL: bit 6 for GPO1 down to bit 3 for GPO4.
   */
  bool setGPOVal(uint8_t port, bool driveHigh);

  /** Read GPIO1 input monitor value
   * @param monitorValue Reference to store the GPIO1 input state (0 or 1)
   * @return True if successful, false otherwise
   * @note Reads GPIO_MON (0x2A) GPIO1_MON, bit 7. Only meaningful when GPIO1
   *       is configured as GPI (GPIO_MODE_GPI).
   */
  bool getGPIOMonitorValue(uint8_t &monitorValue);

  /** Read GPI input monitor value
   * @param port GPI port number (1-4)
   * @param monitorValue Reference to store the GPI input state (0 or 1)
   * @return True if successful, false otherwise
   * @note Reads GPI_MON (0x2F) GPIx_MON: bit 7 for GPI1 down to bit 4 for
   *       GPI4. Only meaningful when the port is configured as GPI.
   */
  bool getGPIMonitorValue(uint8_t port, uint8_t &monitorValue);

  /** Configure GPO port function and drive mode
   * @param port GPO port number (1-4)
   * @param mode GPO function mode (disabled, GPO, IRQ, ASI, PDM)
   * @param driveMode DRIVE_MODE_HI_Z or DRIVE_MODE_ACTIVE_LOW_ACTIVE_HIGH;
   *        any other value returns false
   * @return True if successful, false otherwise
   * @note Writes the whole GPO_CFGx register (0x22-0x25, one per port):
   *       GPOx_CFG bits 7:4 and GPOx_DRV bit 0. See datasheet 6.3.7.
   */
  bool setGPOMode(uint8_t port, GPOMode mode, DriveMode driveMode);

  /** Configure GPI port function
   * @param port GPI port number (1-4)
   * @param mode GPI function mode (disabled, GPI, MCLK, ASI, PDM)
   * @return True if successful, false otherwise
   * @note Writes GPI_CFG0 (0x2B) for ports 1-2 or GPI_CFG1 (0x2C) for ports
   *       3-4; odd ports use bits 6:4, even ports bits 2:0. See datasheet 6.3.7.
   */
  bool setGPIMode(uint8_t port, GPIMode mode);

  /** Select or deselect PDM as the input source for a port's two channels
   * @param port PDM input port number (1-4); port p covers channels 2p-1 and 2p
   * @param enable True for PDM input, false for input source not enabled
   * @return True if successful, false otherwise
   * @note Writes CHx_INSRC (CHx_CFG0 bits 6:5) for both channels of port 1
   *       (CH1, CH2) or port 2 (CH3, CH4). Channels 5-8 are always PDM inputs,
   *       so ports 3 and 4 have nothing to configure and return true. Does
   *       not configure the GPO/GPI pins; see configurePDMInput(). See
   *       datasheet 7.1.2.36 to 7.1.2.52.
   */
  bool enablePort(uint8_t port, bool enable);

  /** Enable or disable input channels
   * @param chMask Bit mask for channels 1-8 (bit 7 = Ch1, bit 0 = Ch8)
   * @return True if successful, false otherwise
   * @note Writes the whole IN_CH_EN (0x73) register. Reset default is 0xF0
   *       (channels 1-4 enabled).
   */
  bool enableChannels(uint8_t chMask);

  /** Enable or disable ASI output channels
   * @param chMask Bit mask for channels 1-8 (bit 7 = Ch1, bit 0 = Ch8)
   * @return True if successful, false otherwise
   * @note Writes the whole ASI_OUT_CH_EN (0x74) register. A disabled
   *       channel's output slot is tri-stated.
   */
  bool enableOutputASIChannels(uint8_t chMask);

  /** Assign input channel to ASI output slot
   * @param channel Input channel number (1-8)
   * @param slot ASI output slot (0-63)
   * @return True if successful, false otherwise
   * @note Writes ASI_CHx (0x0B-0x12) CHx_SLOT, bits 5:0. In I2S/LJ mode,
   *       slots 0-31 are left slots and 32-63 are right slots 0-31.
   */
  bool setASISlotAssignment(uint8_t channel, uint8_t slot);

  /** Set ASI output line for a channel
   * @param channel Channel number (1-8)
   * @param asiPin Primary or secondary ASI output line
   * @return True if successful, false otherwise
   * @note Writes ASI_CHx (0x0B-0x12) CHx_OUTPUT, bit 6.
   */
  bool setASIOutputLine(uint8_t channel, ASIPin asiPin);

  /** Configure PDM input latch edge mode
   * @param port PDM port number (1-4)
   * @param mode Edge on which the even-numbered channel is latched
   * @return True if successful, false otherwise
   * @note Writes PDMIN_CFG (0x20) PDMDINx_EDGE: bit 7 for port 1 down to
   *       bit 4 for port 4.
   */
  bool setPortEdgeLatchMode(uint8_t port, EdgeLatchMode mode);

  /** Set digital volume for a channel
   * @param channel Channel number (1-8)
   * @param volume Volume value (0-255 in 0.5dB steps, where 0xC9 is unity gain)
   * @return True if successful, false otherwise
   * @note Writes CHx_CFG2 (0x3E + 5 * (channel - 1)) CHx_DVOL. 0 = mute,
   *       1 = -100dB, 0xC9 = 0dB (reset default), 0xFF = +27dB. See datasheet
   *       6.3.6.1.
   */
  bool setDigitalVolume(uint8_t channel, uint8_t volume);

  /** Set gain calibration for a channel
   * @param channel Channel number (1-8)
   * @param gainCalibration Gain calibration value (0-15): 0 = -0.8dB,
   *        8 = 0dB (reset default), 15 = +0.7dB, in 0.1dB steps
   * @return True if successful, false otherwise
   * @note Writes CHx_CFG3 (0x3F + 5 * (channel - 1)) CHx_GCAL, bits 7:4.
   *       See datasheet 6.3.6.2.
   */
  bool setGainCalibration(uint8_t channel, uint8_t gainCalibration);

  /** Set phase calibration (delay) for a channel
   * @param channel Channel number (1-8)
   * @param phaseCalibration Delay in modulator clock cycles (0-255, ~163 ns each)
   * @return True if successful, false otherwise
   * @note Writes CHx_CFG4 (0x40 + 5 * (channel - 1)) CHx_PCAL, bits 7:0.
   *       See datasheet 6.3.6.3.
   */
  bool setPhaseCalibration(uint8_t channel, uint8_t phaseCalibration);

  /** Set decimation filter mode
   * @param mode Filter mode (linear, low latency, or ultra-low latency)
   * @return True if successful, false otherwise
   * @note Writes DSP_CFG0 (0x6B) DECI_FILT, bits 5:4. See datasheet 6.3.6.7
   *       for each filter's response.
   */
  bool setDecimationFilterMode(FilterMode mode);

  /** Configure channel summation mode
   * @param mode Summation mode (disabled, 2-channel, or 4-channel)
   * @return True if successful, false otherwise
   * @note Writes DSP_CFG0 (0x6B) CH_SUM, bits 3:2. See datasheet 6.3.6.6.
   */
  bool setChannelSummationMode(SummationMode mode);

  /** Configure high-pass filter mode
   * @param mode HPF mode (custom, 12Hz, 96Hz, or 384Hz at 48kHz)
   * @return True if successful, false otherwise
   * @note Writes DSP_CFG0 (0x6B) HPF_SEL, bits 1:0. The custom filter's
   *       coefficients (page 4) are not set by this library. See datasheet
   *       6.3.6.4.
   */
  bool setHighpassFilterMode(HPFilterMode mode);

  /** Configure digital volume as ganged or independent
   * @param gangedDigitalVolume True for all active channels to use the
   *        channel 1 volume (CH1_DVOL), false for per-channel volume
   * @return True if successful, false otherwise
   * @note Writes DSP_CFG1 (0x6C) DVOL_GANG, bit 7.
   */
  bool setDigitalVolumeConfig(bool gangedDigitalVolume);

  /** Configure number of biquad filters per channel
   * @param numBiquads Number of biquads per channel (0-3; reset default 2)
   * @return True if successful, false otherwise
   * @note Writes DSP_CFG1 (0x6C) BIQUAD_CFG, bits 6:5. The biquad
   *       coefficients (pages 2-4) are not set by this library. See datasheet
   *       6.3.6.5.
   */
  bool setBiquadConfig(uint8_t numBiquads);

  /** Enable or disable soft-stepping during volume change, mute and unmute
   * @param softStepEnabled True to enable soft-stepping (reset default)
   * @return True if successful, false otherwise
   * @note Writes DSP_CFG1 (0x6C) DISABLE_SOFT_STEP, bit 4, which is a disable
   *       bit (0 = enabled).
   */
  bool setSoftStepEnabled(bool softStepEnabled);

  /** Control microphone bias power supply
   * @param power True to power on, false to power off
   * @return True if successful, false otherwise
   * @note Writes PWR_CFG (0x75) MICBIAS_PDZ, bit 7. See datasheet 6.3.4.
   */
  bool powerMICBIAS(bool power);

  /** Control PDM channel power
   * @param power True to power up all enabled PDM channels, false to power
   *        down all PDM channels
   * @return True if successful, false otherwise
   * @note Writes PWR_CFG (0x75) PDM_PDZ, bit 6. The datasheet (6.4.3) says to
   *       configure IN_CH_EN and ASI_OUT_CH_EN before writing PWR_CFG.
   */
  bool powerPDM(bool power);

  /** Control PLL power
   * @param power True to power on, false to power off
   * @return True if successful, false otherwise
   * @note Writes PWR_CFG (0x75) PLL_PDZ, bit 5. See datasheet 6.3.2.
   */
  bool powerPLL(bool power);

  /** Configure dynamic channel power-up/power-down
   * @param enableDynamicPowerUp True to allow channels to be powered up or
   *        down individually while recording is on
   * @param mode Channels used with the dynamic feature (Ch1-2, 1-4, 1-6, or all)
   * @return True if successful, false otherwise
   * @note Writes PWR_CFG (0x75) DYN_CH_PUPD_EN (bit 4) and DYN_MAXCH_SEL
   *       (bits 3:2).
   */
  bool setDynamicPowerUpConfig(bool enableDynamicPowerUp, DynamicPowerMode mode);

  /** Wake up the device from sleep mode
   * @return True if successful, false otherwise
   * @note Writes SLEEP_CFG (0x02) once, setting SLEEP_ENZ (bit 0) and
   *       AREG_SELECT (bit 7) together, as the datasheet requires AREG to be
   *       configured while exiting sleep and allows no other I2C transactions
   *       in sleep mode. VREF_QCHG and I2C_BRDCAST_EN are restored from the
   *       value saved by sleep() (reset defaults after begin(), reset() or
   *       hardwarePowerUp()). Then waits 1ms, and if AVDD is 1.8V sets
   *       BIAS_CFG VREF_SEL to 1.375V. See datasheet 6.4.2 and 6.4.3.
   */
  bool wakeUp();

  /** Put the device into sleep mode
   * @return True if successful, false otherwise
   * @note Reads and saves SLEEP_CFG (0x02), clears SLEEP_ENZ (bit 0), then
   *       waits 10ms, as required before the next I2C transaction. Register
   *       values are retained. Only call wakeUp(), reset() or
   *       hardwarePowerDown() while asleep. See datasheet 6.4.2.
   */
  bool sleep();

  /** Release hardware shutdown by driving the SHDNZ pin high
   * @return True if successful, false if SHDNZ pin not configured
   * @note Waits 1ms afterwards. When SHDNZ goes high, the device resets all
   *       registers to their defaults and enters sleep mode. See datasheet
   *       6.4.1.
   */
  bool hardwarePowerUp();

  /** Enter hardware shutdown by driving the SHDNZ pin low
   * @return True if successful, false if SHDNZ pin not configured
   * @note Waits 50ms afterwards. In hardware shutdown all registers are lost
   *       and I2C is not available; SHDNZ must stay low for at least 1ms
   *       after the device enters shutdown. See datasheet 6.4.1.
   */
  bool hardwarePowerDown();

  /** Set internal or external AREG source
   * @param internal True for the internally generated 1.8V AREG (use when
   *        AVDD is 3.3V), false for an external 1.8V AREG supply (use when
   *        AVDD is 1.8V, with AREG shorted to AVDD)
   * @return True if successful, false otherwise
   * @note Writes SLEEP_CFG (0x02) AREG_SELECT, bit 7, and stores the choice
   *       for the next wakeUp(). The datasheet (6.4.2) says to configure AREG
   *       while exiting sleep mode, which wakeUp() does; call this only while
   *       the device is active.
   */
  bool setAREG(bool internal);

  /** Set the VREF quick-charge duration
   * @param duration Charge duration (3.5ms, 10ms, 50ms, or 100ms)
   * @return True if successful, false otherwise
   * @note Writes SLEEP_CFG (0x02) VREF_QCHG, bits 4:3. See datasheet 6.3.3.
   */
  bool setVREFQuickChargeDuration(VREFChargeDuration duration);

  /** Set what DREG does after the SHDNZ pin is asserted
   * @param mode Shutdown mode
   * @return True if successful, false otherwise
   * @note Writes SHDN_CFG (0x05) SHDNZ_CFG, bits 3:2. See datasheet 6.4.1.
   */
  bool setShutdownMode(ShutdownMode mode);

  /** Set how long DREG remains active after SHDNZ is asserted
   * @param time DREG active timing (5ms, 10ms, 25ms, or 30ms)
   * @return True if successful, false otherwise
   * @note Writes SHDN_CFG (0x05) DREG_KA_TIME, bits 1:0.
   */
  bool setDREGActiveTime(DREGActiveTime time);

  /** Configure microphone bias and VREF voltage
   * @param micbiasMode Bias source (VREF or AVDD)
   * @param vrefMode VREF voltage (2.75V, 2.5V, or 1.375V)
   * @return True if successful, false otherwise
   * @note Writes the whole BIAS_CFG (0x3B) register: MBIAS_VAL bits 6:4 and
   *       VREF_SEL bits 1:0. See datasheet 6.3.3 and 6.3.4.
   */
  bool configureBias(MICBIASMode micbiasMode, VREFMode vrefMode);

  /** Configure interrupt pin behavior
   * @param mode Interrupt event mode (constant, 2ms pulsed, or 2ms once)
   * @param latchMode Latch read mode (all or unmasked only)
   * @param polarity Interrupt polarity (active low or active high)
   * @return True if successful, false otherwise
   * @note Writes the whole INT_CFG (0x32) register: INT_POL bit 7,
   *       INT_EVENT bits 6:5 and LTCH_READ_CFG bit 2. See datasheet 6.3.7.
   */
  bool setInterruptConfig(INTMode mode, INTLatchReadMode latchMode, INTPolarity polarity);

  /** Mask or unmask interrupt sources
   * @param maskAsiClockError True to mask the ASI clock error interrupt
   * @param maskPllLockInterrupt True to mask the PLL lock interrupt
   * @return True if successful, false otherwise
   * @note Writes INT_MASK0 (0x33) bit 7 (ASI clock error) and bit 6
   *       (PLL lock).
   */
  bool setInterruptMasks(bool maskAsiClockError, bool maskPllLockInterrupt);

  /** Write a single register value
   * @param reg Register address
   * @param value Value to write
   * @return True if write successful, false otherwise
   * @note Single-byte I2C write on the current register page. See datasheet
   *       6.5.1.1.2.1.
   */
  bool writeRegister(uint8_t reg, uint8_t value);

  /** Read a single register value
   * @param reg Register address
   * @param value Reference to store the read value
   * @return True if read successful, false otherwise
   * @note Single-byte I2C read (write address, repeated start, read) on the
   *       current register page. See datasheet 6.5.1.1.2.3.
   */
  bool readRegister(uint8_t reg, uint8_t &value);

  /** Update specific bits in a register (read-modify-write)
   * @param reg Register address
   * @param mask Bit mask indicating which bits to update
   * @param value New value for masked bits
   * @return True if update successful, false otherwise
   * @note Reads the register, replaces the bits in mask with the matching
   *       bits of value, and writes it back.
   */
  bool updateRegisterBits(uint8_t reg, uint8_t mask, uint8_t value);

  /** Check if device is present and responding on I2C bus
   * @return True if device is connected, false otherwise
   * @note Sends an empty I2C transmission to the device address and checks
   *       for an acknowledge. Returns false if begin() has not been called.
   */
  bool isConnected();

  /** Read device status registers
   * @param status0 Reference to store the DEV_STS0 (0x76) value: per-channel
   *        PDM power status, bit 7 = Ch1 to bit 0 = Ch8 (1 = powered up)
   * @param deviceModeStatus Reference to store DEV_STS1 (0x77) MODE_STS,
   *        bits 7:5: 4 = sleep or software shutdown, 6 = active with all PDM
   *        channels off, 7 = active with at least one PDM channel on
   * @return True if read successful, false otherwise
   */
  bool getDeviceStatus(uint8_t &status0, uint8_t &deviceModeStatus);

  /** Read latched interrupt status flags
   * @param asiBusClockError Reference to store the ASI bus clock error flag
   * @param pllLockError Reference to store the PLL lock interrupt flag
   * @return True if read successful, false otherwise
   * @note Reads INT_LTCH0 (0x36) bits 7 and 6. The bits are self-clearing,
   *       so reading them clears the latched interrupts.
   */
  bool getLatchedInterruptStatus(bool &asiBusClockError, bool &pllLockError);

  /** Read the auto-detected ASI sample rate and BCLK ratio
   * @param fsRate Reference to store the detected sample rate. Each FSRate
   *        value covers a 44.1kHz-family and a 48kHz-family rate (e.g.
   *        FSRATE_48 is 44.1kHz or 48kHz); the device does not report which.
   * @param ratio Reference to store detected BCLK/FSYNC ratio
   * @return True if read successful, false if the read failed or the
   *         register reports an invalid or reserved value
   * @note Reads ASI_STS (0x15): FS_RATE_STS bits 7:4 and FS_RATIO_STS bits
   *       3:0. See datasheet 6.3.2.
   */
  bool getAutodetectedClocks(FSRate &fsRate, uint32_t &ratio);

private:
  // Register address constants
  static constexpr uint8_t REG_PAGE_SELECT   = 0x00;
  static constexpr uint8_t REG_SW_RESET      = 0x01;
  static constexpr uint8_t REG_SLEEP_CFG     = 0x02;
  static constexpr uint8_t REG_SHDN_CFG      = 0x05;
  static constexpr uint8_t REG_ASI_CFG0      = 0x07;
  static constexpr uint8_t REG_ASI_CFG1      = 0x08;
  static constexpr uint8_t REG_ASI_CFG2      = 0x09;
  static constexpr uint8_t REG_ASI_CH1       = 0x0B;
  static constexpr uint8_t REG_ASI_CH2       = 0x0C;
  static constexpr uint8_t REG_ASI_CH3       = 0x0D;
  static constexpr uint8_t REG_ASI_CH4       = 0x0E;
  static constexpr uint8_t REG_ASI_CH5       = 0x0F;
  static constexpr uint8_t REG_ASI_CH6       = 0x10;
  static constexpr uint8_t REG_ASI_CH7       = 0x11;
  static constexpr uint8_t REG_ASI_CH8       = 0x12;
  static constexpr uint8_t REG_MST_CFG0      = 0x13;
  static constexpr uint8_t REG_MST_CFG1      = 0x14;
  static constexpr uint8_t REG_ASI_STS       = 0x15;
  static constexpr uint8_t REG_CLK_SRC       = 0x16;
  static constexpr uint8_t REG_PDMCLK_CFG    = 0x1F;
  static constexpr uint8_t REG_PDMIN_CFG     = 0x20;
  static constexpr uint8_t REG_GPIO_CFG0     = 0x21;
  static constexpr uint8_t REG_GPO_CFG0      = 0x22;
  static constexpr uint8_t REG_GPO_CFG1      = 0x23;
  static constexpr uint8_t REG_GPO_CFG2      = 0x24;
  static constexpr uint8_t REG_GPO_CFG3      = 0x25;
  static constexpr uint8_t REG_GPO_VAL       = 0x29;
  static constexpr uint8_t REG_GPIO_MON      = 0x2A;
  static constexpr uint8_t REG_GPI_CFG0      = 0x2B;
  static constexpr uint8_t REG_GPI_CFG1      = 0x2C;
  static constexpr uint8_t REG_GPI_MON       = 0x2F;
  static constexpr uint8_t REG_INT_CFG       = 0x32;
  static constexpr uint8_t REG_INT_MASK0     = 0x33;
  static constexpr uint8_t REG_INT_LTCH0     = 0x36;
  static constexpr uint8_t REG_BIAS_CFG      = 0x3B;
  static constexpr uint8_t REG_CH1_CFG0      = 0x3C;
  static constexpr uint8_t REG_CH1_CFG2      = 0x3E;
  static constexpr uint8_t REG_CH1_CFG3      = 0x3F;
  static constexpr uint8_t REG_CH1_CFG4      = 0x40;
  static constexpr uint8_t REG_CH2_CFG0      = 0x41;
  static constexpr uint8_t REG_CH2_CFG2      = 0x43;
  static constexpr uint8_t REG_CH2_CFG3      = 0x44;
  static constexpr uint8_t REG_CH2_CFG4      = 0x45;
  static constexpr uint8_t REG_CH3_CFG0      = 0x46;
  static constexpr uint8_t REG_CH3_CFG2      = 0x48;
  static constexpr uint8_t REG_CH3_CFG3      = 0x49;
  static constexpr uint8_t REG_CH3_CFG4      = 0x4A;
  static constexpr uint8_t REG_CH4_CFG0      = 0x4B;
  static constexpr uint8_t REG_CH4_CFG2      = 0x4D;
  static constexpr uint8_t REG_CH4_CFG3      = 0x4E;
  static constexpr uint8_t REG_CH4_CFG4      = 0x4F;
  static constexpr uint8_t REG_CH5_CFG0      = 0x50;
  static constexpr uint8_t REG_CH5_CFG2      = 0x52;
  static constexpr uint8_t REG_CH5_CFG3      = 0x53;
  static constexpr uint8_t REG_CH5_CFG4      = 0x54;
  static constexpr uint8_t REG_CH6_CFG0      = 0x55;
  static constexpr uint8_t REG_CH6_CFG2      = 0x57;
  static constexpr uint8_t REG_CH6_CFG3      = 0x58;
  static constexpr uint8_t REG_CH6_CFG4      = 0x59;
  static constexpr uint8_t REG_CH7_CFG0      = 0x5A;
  static constexpr uint8_t REG_CH7_CFG2      = 0x5C;
  static constexpr uint8_t REG_CH7_CFG3      = 0x5D;
  static constexpr uint8_t REG_CH7_CFG4      = 0x5E;
  static constexpr uint8_t REG_CH8_CFG0      = 0x5F;
  static constexpr uint8_t REG_CH8_CFG2      = 0x61;
  static constexpr uint8_t REG_CH8_CFG3      = 0x62;
  static constexpr uint8_t REG_CH8_CFG4      = 0x63;
  static constexpr uint8_t REG_DSP_CFG0      = 0x6B;
  static constexpr uint8_t REG_DSP_CFG1      = 0x6C;
  static constexpr uint8_t REG_IN_CH_EN      = 0x73;
  static constexpr uint8_t REG_ASI_OUT_CH_EN = 0x74;
  static constexpr uint8_t REG_PWR_CFG       = 0x75;
  static constexpr uint8_t REG_DEV_STS0      = 0x76;
  static constexpr uint8_t REG_DEV_STS1      = 0x77;
  static constexpr uint8_t REG_I2C_CKSUM     = 0x7E;
  
  uint8_t _i2cAddr;
  TwoWire *_wire;
  bool _initialized;
  uint8_t _shdnzPin;
  bool _aregInternal;
  AVDDInputVoltage _avddInputVoltage;
  uint8_t _sleepCfg;  // Last known SLEEP_CFG value, restored by wakeUp()
};

#endif // PCMD3180_H